name: hid
version: '0.2.2'
synopsis: Interface to hidapi library
description: ! 'Requires the hidapi-libusb C API and pkg-config.


  For information

  <https://github.com/signal11/hidapi/tree/master/libusb here>'
category: System
author: Dimitri Sabadie <dimitri.sabadie@gmail.com>
maintainer: Dimitri Sabadie <dimitri.sabadie@gmail.com>
copyright: Dimitri Sabadie
license: BSD3
extra-source-files:
- CHANGELOG.md
default-extensions:
- CPP
ghc-options:
- -W
- -Wall
include-dirs:
- include
c-sources:
- cbits/hid.c
extra-libraries:
- SetupAPI
build-tools:
- c2hs
dependencies:
- base >=4.8 && <5.0
- bytestring >=0.10 && <0.11
- transformers >=0.4 && <0.6
library:
  source-dirs: src
  when:
  - condition: flag(stdcall)
    then:
      cpp-options: -DCALLCV=stdcall
    else:
      cpp-options: -DCALLCV=ccall
  - condition: ! '!(os(windows))'
    dependencies:
    - unbuildable <0
flags:
  stdcall:
    description: Use the stdcall call convention
    manual: false
    default: false
